a=("tusker project fame was once the biggest show in kenya")
print(a)
c=(1,2,3,4,5)
print(c)
num1=(15)
num2=(20)
sum=num1+num2
print(sum)
num3=(34)
num4=(45)
multiplication=num3*num4
print(multiplication)
name=("khalid")
print(f"my name is",name)
print("my name is {}".format(name))
print("I wil now count my chicken")
print("Hen",25+30/6)
print("Roosters",1000-25*3%4)
print("Now I will count the eggs")
print(3+2+1-5%2-1/4+6)
print("Is it true that 3+2<5-7?")
print(3+2<5-7)
print("what is 3+2?",3+2)
print("what is 5-7?",5-7)
print("Oh about some more.")
print("Is it greater?,5>-2")
print("iS IT greater or equal?",5>=-2)
print("Is it less or equal",5<=-2)


